#! /bin/bash

set -euo pipefail

readonly RESOURCES=$(pwd)/resources
readonly BINARIES=$RESOURCES/binaries
readonly PROPERTIES_FILES=$RESOURCES/properties
readonly XML_FILES=$RESOURCES/xml

readonly RES='\e[0m'
readonly RED='\e[0;31m'
readonly GRE='\e[0;32m'
readonly YEL='\e[0;33m'
readonly BRED='\e[1;31m'
readonly BGRE='\e[1;32m'
readonly BYEL='\e[1;33m'

# default destination url for fhir testing
URL="http://localhost:80/aktin/cda/fhir/Binary/"

# set timestamp to compare saving of sent CDA files
CURRENT_HOUR=$(date "+%Y-%m-%d %H")

# loop over all storyboards
STORYBOARD=( 01 01_error 02 03 01)
CODE=( 201 422 201 201 200)
for i in "${!STORYBOARD[@]}"
do
	# sent CDA document via java-demo-server-fhir-client and catch response
	RESPONSE=$(java -Djava.util.logging.config.file="$PROPERTIES_FILES/logging.properties" -cp "$BINARIES/demo-server-0.14.jar" org.aktin.cda.etl.demo.client.FhirClient $URL $XML_FILES/storyboard${STORYBOARD[$i]}.xml 2<&1)

	# extract response code and compare with predefined code, print whole response on failure
	RESPONSE_CODE=$(echo $RESPONSE | grep -oP '(?<=Response code: )[0-9]+')
	if [[ $RESPONSE_CODE == ${CODE[$i]} ]]; then
		echo -e "${GRE}storyboard${STORYBOARD[$i]} successful ($RESPONSE_CODE)${RES}"
	else
		echo -e "${RED}storyboard${STORYBOARD[$i]} failed ($RESPONSE_CODE)${RES}"
		echo $RESPONSE
	fi
done

# count entries in i2b2crcdata with import_date within previously set timestamp
if [[ $(sudo -u postgres psql -d i2b2 -v ON_ERROR_STOP=1 -c "SELECT import_date FROM i2b2crcdata.encounter_mapping" | grep -c "$CURRENT_HOUR") != 0 ]]; then
	echo -e "${GRE} --> new entries in i2b2 detected${RES}"
else
	echo -e "${RED} --> no new entries in i2b2 detected${RES}"
fi
