#! /bin/bash

set -euo pipefail

# default destination url for fhir testing
URL="http://localhost:80/aktin/cda/fhir/Binary/"

# set timestamp to compare saving of sent CDA files

# loop over all storyboards
STORYBOARD=( 01 02 03 04 05 06 )
for i in "${!STORYBOARD[@]}"
do
	# sent CDA document via java-demo-server-fhir-client and catch response
	RESPONSE=$(java -cp "demo-server-0.14.jar" org.aktin.cda.etl.demo.client.FhirClient $URL storyboard${STORYBOARD[$i]}.xml 2<&1)

	# extract response code and compare with predefined code, print whole response on failure
	RESPONSE_CODE=$(echo $RESPONSE | grep -oP '(?<=Response code: )[0-9]+')
	if [[ $RESPONSE_CODE == ${CODE[$i]} ]]; then
		echo -e "${GRE}storyboard${STORYBOARD[$i]} successful ($RESPONSE_CODE)${RES}"
	else
		echo -e "${RED}storyboard${STORYBOARD[$i]} failed ($RESPONSE_CODE)${RES}"
		echo $RESPONSE
	fi
done
