#!/bin/bash
#--------------------------------------
# Script Name:  preinst
# Version:      1.0
# Author:       skurka@ukaachen.de, shuening@ukaachen.de, akombeiz@ukaachen.de
# Date:         29 Oct 24
# Purpose:      Pre-installation script for 'aktin'. This script stops the WildFly service to prepare for package installation
#               or upgrade, and backs up the existing aktin properties file if upgrading.
#--------------------------------------

readonly OPERATION="${1}"

backup_aktin_properties() {
  local path_properties="/etc/aktin/aktin.properties"
  if [[ -f "$path_properties" ]]; then
    local backup_path="/etc/aktin/backup_$(date +%Y_%m_%d_%H%M).properties"
    cp -f "$path_properties" "$backup_path"
    echo "Backup of aktin.properties created at $backup_path"
  fi
}

main() {
  set -euo pipefail
  case "$OPERATION" in
    upgrade)
      backup_aktin_properties
      ;;
  esac
}

main "$@"
