services:
  database:
    image: ${IMAGE_NAMESPACE}-database
    build: build/database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: >
        psql -U postgres -lqt | cut -d \| -f 1 | grep -qw aktin
      interval: 1s
      timeout: 1s
      retries: 120
  httpd:
    image: ${IMAGE_NAMESPACE}-httpd
    build: build/httpd
  wildfly:
    image: ${IMAGE_NAMESPACE}-wildfly
    build: build/wildfly
    depends_on:
      database:
        condition: service_healthy
