#!/bin/bash
set -e

. /usr/share/debconf/confmodule

case "$1" in
	remove)
		db_input high $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_proxy_http || true
		db_go || true
		db_fset $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_proxy_http seen false
		db_get $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_proxy_http
		if [ "$RET" = "Yes" ]; then
			echo "Disabling apache2 proxy_http module ..."
			a2dismod proxy_http >/dev/null || true
		fi
		a2disconf aktin-j2ee-reverse-proxy >/dev/null 2>&1 || true
		systemctl restart apache2.service || true

		rm -f /opt/wildfly/standalone/deployments/dwh-j2ee-*
		rm -f /opt/wildfly/standalone/deployments/aktin-ds.xml
		rm -f /opt/wildfly/standalone/deployments/aktin-ds.xml.*
		;;
	purge)
		I2B2_SHARED=$(echo $DPKG_MAINTSCRIPT_PACKAGE | awk -F '-' '{print $1"-"$2}')
		PSQL=""
		db_get $I2B2_SHARED/db_conn
		if [ "$RET" = "unix" ]; then
			PSQL="sudo -u postgres psql"
			echo "Connecting to postgres via local unix socket."
		else
			db_get $I2B2_SHARED/db_host
			host="$RET"
			db_get $I2B2_SHARED/db_port
			port="$RET"
			db_get $I2B2_SHARED/db_user
			user="$RET"
			db_get $I2B2_SHARED/db_pass
			pass="$RET"
			PSQL="psql postgresql://$user:$pass@$host:$port?sslmode=require"
			echo "Connecting to postgres via TCP/IP to $host:$port."
		fi
		echo "Dropping AKTIN database ..."
		eval "$PSQL -v ON_ERROR_STOP=1" <<EOF >/dev/null
__AKTIN_DROP__

EOF
		# db_purge
		;;
esac

systemctl start wildfly.service 2> /dev/null || true
