name: CI/CD Development

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: aktin/aktin-github-scripts/.github/workflows/debian-build.yml@main
    with:
      package-name: 'aktin-notaufnahme-dwh'

  deploy:
    needs: build
    uses: aktin/aktin-github-scripts/.github/workflows/debian-deploy.yml@main
    with:
      package-name: 'aktin-notaufnahme-dwh'
      package-version: ${{ needs.build.outputs.package-version }}
      codename: 'jammy-unstable'